image: ruby:2.5.1

variables:
  RAILS_ENV: test
  NODE_VERSION: 8.0.0
  POSTGRES_DB: playground5
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - vendor/ruby
    - node_modules

rubocop:
  stage: lint
  before_script:
    - bundle install --path vendor
  script:
    - rubocop
  except:
    - schedules

brakeman:
  stage: lint
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install brakeman
  script:
    - brakeman
  except:
    - schedules

bundler-audit:
  stage: lint
  before_script:
    - gem install bundler-audit
  script:
    - bundle audit
  allow_failure: true

rspec:
  stage: test
  before_script:
    - curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1;
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
    - bundle install --without development --path vendor
    - yarn install
  services:
    - postgres:9.6
  script:
    - bundle exec rake db:migrate
    - bundle exec rspec
  except:
    - schedules

deploy:
  stage: deploy
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
    - bundle install --path vendor
  script:
    - bundle exec cap production deploy
  only:
    - master
  except:
    - schedules
